### ISSUE TITLE
Incompatible with modern yarn setups (v2+)

### ISSUE THREAD

**Issue by ssbarnea** [redhat-developer/vscode-extension-tester#451]
For a project using modern yarn setup extest cannot be used, mainly because it does call vsce with incompatible parameters

```
ChromeDriver 98.0.4758.102 exists in local cache, skipping download
This extension consists of 10210 files, out of which 5357 are JavaScript files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension . You should also exclude unnecessary files by adding them to your .vscodeignore: https://aka.ms/vscode-vscodeignore
 ERROR  invalid relative path: extension/../ansible-language-server/node_modules/@flatten-js/interval-tree/.babelrc
Error: Command failed: node_modules/.bin/vsce package --no-yarn
    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:899:15)
    at CodeUtil.packageExtension (/Users/ssbarnea/c/a/vscode-ansible/node_modules/vscode-extension-tester/out/util/codeUtil.js:170:23)
    at ExTester.<anonymous> (/Users/ssbarnea/c/a/vscode-ansible/node_modules/vscode-extension-tester/out/extester.js:77:27)
    at Generator.next (<anonymous>)
    at /Users/ssbarnea/c/a/vscode-ansible/node_modules/vscode-extension-tester/out/extester.js:18:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/ssbarnea/c/a/vscode-ansible/node_modules/vscode-extension-tester/out/extester.js:14:12)
    at ExTester.installVsix (/Users/ssbarnea/c/a/vscode-ansible/node_modules/vscode-extension-tester/out/extester.js:58:16)
```

The thing important here is `vsce package --no-yarn` which is not the correct way to call vsce command as the one we need is `vsce package --no-dependencies` but we have no control about how it is called.

https://github.com/redhat-developer/vscode-extension-tester/blob/7a4da6df04b26d12854d2e22bf5c5949d53d3e3f/src/util/codeUtil.ts#L189

**Comment by ssbarnea** [comment]
This problem was fixed by the recent release of vsce 2.9.2 which fixed https://github.com/microsoft/vscode-vsce/issues/742 so now you can configure the request options inside package.json instead of trying to pass them to vsce command.

**Comment by ssbarnea** [comment]
In fact not fixed until we bump vsce version.

**Comment by odockal** [comment]
@ssbarnea So you are saying that this issue still occurs until we bump up the vsce version, but the issue is closed? Shouldn't it be opened?

**Comment by odockal** [comment]
Now it seems to be addressed by mentioned PR. Thx for the fix.
