### ISSUE TITLE
[🚫 Bug] Fail on unpackaging the VSCode stable

### ISSUE THREAD

**Issue by buithanhlong1912** [redhat-developer/vscode-extension-tester#906]
> While I tried to run extest get-vscode, I found that after running the get-vscode command, I couldn't open the Code.exe on test resources. And I also get the error descriptions on the terminal like this:

This version of PATH_TO_REPO\test-resources\VSCode-win32-x64-archive\Code.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
Error: Command failed: set ELECTRON_RUN_AS_NODE=1 && PATH-TO-REPO\test-resources\VSCode-win32-x64-archive\Code.exe" "PATH-TO-REPO\test-resources\VSCode-win32-x64-archive\resources\app\out\cli.js" --ms-enable-electron-run-as-node --force --install-extension "PATH-TO-REPO\extensionName.vsix".

Did anyone have any ideas or got this bug? And how to solve this?
Thank you!

**Steps to Reproduce**
1. Install the packages.
2. Set up the script to run commands get-vscode, get-chromedriver, and install-vsix.
3. Run the script that was set up before.
4. Got the error

**Expected behavior**
- Successfully install all the requirements packages without any errors found.

**Environment information**
 - OS:
    - Windows 10 22H2
- VSCode version: 1.81.0 (system setup)
- ExTester version: 5.9.0
- Node (npm) version: v18.16.0

**Comment by djelinek** [comment]
Hello @buithanhlong1912 , htnak you for reporting the issue. May I ask you to test also with Node 16? are you able to still reproduce the problem?

I am asking because vscode-extension-tester is currently supports only Node 16

**Comment by buithanhlong1912** [comment]
I got this while upgrading to v18. But I found the root cause of this one. It's due to selenium-webdriver's version. After I try to install this one manually, the issues were fixed. 
"selenium-webdriver": "4.9.2",
"vscode-extension-tester": "5.6.0",
"vscode-extension-tester-locators": "3.4.2"
I tried this one and it's worked!

**Comment by djelinek** [comment]
@buithanhlong1912 Hello, the issue is still relevant with Node 16 and latest release of vscode-extension-tester?

**Comment by hellyzh** [comment]
after manually unpackage VSCode and chrome driver, it will work for node 18
          7z x ".test-resources/chromedriver_win32.zip" -o".test-resources" -y
          7z x ".test-resources/stable.zip" -o".test-resources/VSCode-win32-x64-archive" -y

**Comment by djelinek** [comment]
Current supported NodeJS version is Node <=18.15.0
